### ISSUE TITLE
Legal & governance: Choose an Open Source License

### ISSUE THREAD

**Issue by s3rrot** [boken-engine/boken-engine#3]
We need to select the most appropriate license for the project. In order to do so, we will research about different types of licenses and options available.

**Comment by da2ce7** [comment]
I would like to point to this wonderful page compiled by the Fedora Community: https://fedoraproject.org/wiki/Licensing:Main

It gives a very good list of the licenses; and what to use them fore.,

**Comment by cgbosse** [comment]
In addition to the License document we should add an explanatory document, as to what the license means and how one can incorporate it into any project. We should explain the compatibilities, and the incompatibilities, and show some examples of the possible combinations. Also it is important to make a clear how to use and display the license for anyone coming to the project be they contributors or users.
