### ISSUE TITLE
Choose the next demo application for Boken Engine

### ISSUE THREAD

**Issue by yeraydavidrodriguez** [boken-engine/boken-engine#30]
Currently, there isn't any App that demonstrates all the Boken Engine features and possibilities. We are planning to make one, and the first step is to decide what will be about.

We have rescued some ideas previously discussed, but new additions to the list of possible contents will be welcomed:

- A visual guide to teach kids or seniors about secure practices when using the internet (email, web, social media...)

- A non-linear interactive fiction, inspired by the "choose your own adventure" books.

- A parody of a popular TV show (like "Game of Thrones") developed as a children's book.

- A postmodern, meta-referential story similar to the acclaimed and ground-breaking "Stanley Parable" videogame, exploring the limits of the media.

- A story about the daily life of children in different countries and cultures (Africa, South-Asia, South-America...) to make children aware about very different cultures and lifestyles.

- A didactical guide about universe surprising facts, similar to the first [demo app](https://github.com/boken-engine/15-universe-facts) but with more features and making wider use of the engine possibilites.

- An Italian food recipes cook book.

- A quick first aid guides application to help the user in several emergency situations (Cardiopulmonary resuscitation, heimlich manoeuvre...), with a UI specially tailored to be quick and clear.

- A collection of murder & mystery tales, each one with a final "who is the murderer?" quiz

**Comment by cgbosse** [comment]
I think that if we want to show its potential we should focus on a visual story game approach. I have been researching online and I would suggest that we focus on an interactive visual story, either manga style or D&D style.

**Comment by cgbosse** [comment]
I can imagine a visual story with a role game element that teaches values such as team work, preparation, perseverance.

**Comment by yeraydavidrodriguez** [comment]
Finally, after analyzing all possible choices for a demo application, we decided to go for the "choose your own adventure" story alternative, settled in a high-fantasy theme.

These are the reasons behind this choice:

- A made-up, fiction story can be tailored to our needs (time, budget, resources...) in terms of length, complexity and art requirements.
- A non-linear, tree-like structure like the typical "choose your own adventure" book is directly translated to our JSON file syntax.
- High-fantasy theme (Lord of the Rings, Game of Thrones, Dungeons & Dragons...) is always a very attractive topic for a large audience.
- Visual stories are one of the main use cases in Boken Engine, probably the most relevant one.
- The art of this showcase demo would be easily reused by other creators to make their own adventures.

The repository of the demo project is here: https://github.com/boken-engine/iakkai-saga-curse-of-blood
