### ISSUE TITLE
Demo - Storyboard - Creation in Markdown

### ISSUE THREAD

**Issue by cgbosse** [boken-engine/boken-engine#82]
We need to create and structure the demo's story board in markdown and define the structuring of it for later Json file use.

**Comment by cgbosse** [comment]
The overall storyboard for the demo is ready.

**Comment by da2ce7** [comment]
Consider https://baj.itch.io/drafft

**Comment by s3rrot** [comment]
As markdown for the IAKKAI Saga demo is already available on https://github.com/boken-engine/iakkai-saga-curse-of-blood/blob/main/script/storyboard_v01.md I think we can close this issue.
